/**
 * @description Configuração de valores das chaves utilizadas para salvar valores no local storage
 */
class LocalStorageKeys {
  GLOSSARY_VERSION = 'G_version'
  GLOSSARY_ITEMS = 'G_itemList'
  GLOSSARY_SHOULD_SYNC = 'G_shouldSync'
  CONTACTS = 'c'
  CONTACTS_LAST_ID = 'c_l_id'
  CONTACTS_UPDATE: string = 'c_updt'
  CONTACTS_DEL: string = 'c_del'
  CONTACTS_VERSION = 'cv'
  CONTACTS_SHOULD_SYNC = 'css'
  USER_VERSION = 'uv'
  USER_SHOULD_SYNC = 'uss'
  EMAIL = 'e'
  PICTURE_URL = 'pu'
  SAVED_PICTURE = 'sp'
  SAVE_PICTURE_WITH_ERROR = 'spwe'
  NAME = 'n'
  GOOGLE_ACCESS_TOKEN = 'gat'
  GOOGLE_EXPIRES_DATE = 'ged'
  AUTH_TOKEN = 'at'
  AUTH_TOKEN_EXPIRES_DATE = 'ated'
  TEMP_AUTH_TOKEN = 'tat'
  REFRESH_TOKEN_REQUIRED = 'rtr'
  LANGUAGE = 'lan'
  APP_SETTINGS_VERSION = 'asv'
  APP_SETTINGS = 'as'
  APP_SETTINGS_SHOULD_SYNC = 'asss'
  PAGE_TEMP = 'pt'
  NOTE_VERSION = 'nv'
  NOTE_COLUMN_VERSION = 'ncv'
  NOTE_SHOULD_SYNC = 'nss'
  NOTE_ORDER_SHOULD_SYNC = 'noss'
  NOTE_COLUMN_SHOULD_SYNC = 'ncss'
  NOTE_COLUMN_ORDER_SHOULD_SYNC = 'ncoss'
  UPDATING_NOTES = 'un'
  UPDATE_NOTES_WITH_ERROR = 'une'
  NOTES_TO_DELETE = 'ntd'
  CONNECTION = 'con'
  LOG_APP_ERROR_SYNC = 'laes'
  FAQ_USER_VERSION = 'fuv'
  FAQ_USER_INFO = 'fui'
  FAQ_ITEMS = 'fi'
  SYNC_STATE = 'ss'
  IS_REFRESHING_ACCESS_TOKEN = 'irat'
  SUCCESS_REFRESHING_ACCESS_TOKEN = 'srat'
  IS_REFRESHING_GOOGLE_ACCESS_TOKEN = 'irgat'
  SUCCESS_REFRESHING_GOOGLE_ACCESS_TOKEN = 'srgat'
  ORIENTATION_STATE = 'os'
}

export default new LocalStorageKeys()
