enum FilterEnum {
  USER__CONTACT__ESSENTIAL_CONTACTS = 0,
  USER__CONTACT__YOUR_CONTACTS = 1,
  STAFF__CONTACT__UNIVERSAL_ESSENTIAL_CONTACTS = 0,
  STAFF__CONTACT__TREATMENT_ESSENTIAL_CONTACTS = 1,
  STAFF__TREATMENT__HAS_USER_QUESTIONS = 2,
}

export default FilterEnum